### ISSUE TITLE
Login half-succeeds / connection error

### ISSUE THREAD

**Issue by Philantrop** [mautrix/instagram#56]
For about 18 hours now, the bridge (dock.mau.dev/mautrix/instagram:latest, pulled about an hour ago) fails to properly connect. It starts normally, upon logging in it reports success but a subsequent ping tells me I'm not actually logged in. 
The log contains the following error:

```
[2022-10-05 09:32:06,754] [ERROR@mau.user.@redacted] Error while connecting to Instagram
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 212, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: CurrentUser.__init__() missing 1 required keyword-only argument: 'biography_product_mentions'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/user.py", line 181, in try_connect
    await self.connect()
  File "/usr/lib/python3.10/site-packages/mautrix_instagram/user.py", line 204, in connect
    resp = await client.current_user()
  File "/opt/mautrix-instagram/mauigpapi/http/account.py", line 29, in current_user
    return await self.std_http_get(
  File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 177, in std_http_get
    return response_type.deserialize(json_data)
  File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 375, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 198, in _dict_to_attrs
    new_items[name] = _try_deserialize(field_meta, value)
  File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 229, in _try_deserialize
    return _deserialize(field.type, value, field.default)
  File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 267, in _deserialize
    return _dict_to_attrs(cls, value, default, default_if_empty=True)
  File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 218, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key biography_product_mentions in CurrentUser

```

**Comment by Gigarange** [comment]
Hey this problem seems to have persisted into the latest build of (dock.mau.dev/mautrix/instagram:lv0.2.1). Please ignore if fixed hasn't been pushed to the latest image yet :).

The log contains the following error:

Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:     return _dict_to_attrs(cls, data)
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 198, in _dict_to_attrs
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:     new_items[name] = _try_deserialize(field_meta, value)
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 229, in _try_deserialize
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:     return _deserialize(field.type, value, field.default)
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 267, in _deserialize
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:     return _dict_to_attrs(cls, value, default, default_if_empty=True)
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 218, in _dict_to_attrs
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]:     raise SerializerError(
Oct 07 22:59:08 mat matrix-mautrix-instagram[998581]: mautrix.types.util.serializable.SerializerError: Missing value for required key biography_product_mentions in CurrentUser
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]: [2022-10-07 13:07:08,600] [ERROR@mau.user.@redacted] Error while connecting to Instagram
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]: Traceback (most recent call last):
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 212, in _dict_to_attrs
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     obj = attrs_type(**new_items)
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]: TypeError: CurrentUser.__init__() missing 1 required keyword-only argument: 'biography_product_mentions'
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]: The above exception was the direct cause of the following exception:
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]: Traceback (most recent call last):
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix_instagram/user.py", line 181, in try_connect
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     await self.connect()
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix_instagram/user.py", line 204, in connect
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     resp = await client.current_user()
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/opt/mautrix-instagram/mauigpapi/http/account.py", line 29, in current_user
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     return await self.std_http_get(
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/opt/mautrix-instagram/mauigpapi/http/base.py", line 177, in std_http_get
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     return response_type.deserialize(json_data)
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 375, in deserialize
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     return _dict_to_attrs(cls, data)
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 198, in _dict_to_attrs
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     new_items[name] = _try_deserialize(field_meta, value)
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 229, in _try_deserialize
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     return _deserialize(field.type, value, field.default)
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 267, in _deserialize
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     return _dict_to_attrs(cls, value, default, default_if_empty=True)
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:   File "/usr/lib/python3.10/site-packages/mautrix/types/util/serializable_attrs.py", line 218, in _dict_to_attrs
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]:     raise SerializerError(
Oct 07 23:07:08 mat matrix-mautrix-instagram[998581]: mautrix.types.util.serializable.SerializerError: Missing value for required key biography_product_mentions in CurrentUser

**Comment by bramenn** [comment]
use the latest for now
